/*
 * Copyright 2025 The Go-Spring Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Package StarterHTTPClient wires declarative HTTP clients into the Go-Spring
// container. It is the runtime half of the OpenFeign / @HttpExchange equivalent:
// the call sites are generated by gs-http-gen (they hold only a Target), and
// this starter assembles the process-wide transport those calls dispatch
// through (by replacing httpclt.DoRequest) with service discovery, load
// balancing, resilience and trace propagation already in place — so a
// microservice call no longer means hand-wiring a discovery resolver and a
// circuit breaker per client.
package StarterHTTPClient

import (
	"context"
	"io"
	"net/http"
	"slices"
	"sync"

	"go-spring.org/cloud/experimental/httpx"
	"go-spring.org/cloud/governance/resilience"
	"go-spring.org/log"
	"go-spring.org/spring/conf"
	"go-spring.org/spring/gs"
	"go-spring.org/stdlib/errutil"
	"go-spring.org/stdlib/flatten"
	"go-spring.org/stdlib/httpclt"
	"go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"
)

var starterTag = log.RegisterAppTag("http_client", "")

// clientConfig couples a bound instance name with its Config for the global
// assembler.
type clientConfig struct {
	name string
	cfg  Config
}

func init() {
	// Assemble one process-wide transport and replace httpclt.DoRequest with it.
	// The config is multi-entry (spring.http-client.*), but the transport is
	// single: every entry contributes one route to the shared dispatch transport,
	// keyed by its target (addr or service-name). A generated client therefore
	// only carries a Target, and the runtime routes it through this one
	// transport. The bean is exported as a Rooter so it is instantiated even when
	// nothing autowires it.
	gs.Module(gs.OnProperty("spring.http-client"), func(r gs.BeanProvider, p flatten.Storage) error {
		var cfgs []clientConfig
		if err := conf.BindEach(p, "${spring.http-client}", func(name string, c Config) error {
			cfgs = append(cfgs, clientConfig{name: name, cfg: c})
			return nil
		}); err != nil {
			return err
		}
		r.Provide(installDispatch,
			gs.IndexArg(1, gs.ValueArg(cfgs)),
		).Destroy(destroyDispatch).Export(gs.As[gs.Rooter]()).Caller(1)
		return nil
	})
}

// installDispatch assembles the process-wide dispatch transport (one route per
// configured entry) and replaces httpclt.DoRequest with an implementation that
// routes each request through it. Each entry's transport carries the otelhttp
// base, discovery + load balancing, resilience and any user middleware.
//
// The client is deliberately constructed without a Timeout: per-target timeouts
// belong to the resilience policy of each entry, not to a single process-wide
// hard timeout that would apply to every route.
func installDispatch(ctx *gs.ContextProvider, cfgs []clientConfig) (*dispatchTransport, error) {
	d := &dispatchTransport{routes: make(map[string]http.RoundTripper)}
	for _, cc := range cfgs {
		rt, closeFn, err := assembleTransport(ctx, cc.name, cc.cfg)
		if err != nil {
			return nil, err
		}
		d.routes[routeKey(cc.cfg)] = rt
		if closeFn != nil {
			d.closers = append(d.closers, closeFn)
		}
	}
	client := &http.Client{Transport: d}
	httpclt.DoRequest = func(req *http.Request, meta httpclt.Metadata, fn func(io.Reader) error) (*http.Response, error) {
		resp, err := client.Do(req)
		if err != nil {
			return nil, err
		}
		defer func() { _ = resp.Body.Close() }()
		if err = fn(resp.Body); err != nil {
			return nil, err
		}
		return resp, nil
	}
	log.Infof(ctx.Context, starterTag, "http client initialized, routes=%d", len(d.routes))
	return d, nil
}

// assembleTransport assembles one entry's RoundTripper: otelhttp base → httpx
// discovery/load-balancing/resilience → user middleware. closeFn (when non-nil)
// releases the discovery watch and resilience executor behind it.
func assembleTransport(ctx *gs.ContextProvider, name string, c Config) (rt http.RoundTripper, closeFn func() error, err error) {
	log.Debugf(ctx.Context, starterTag, "assembling http transport, addr=%s service-name=%s", c.Addr, c.ServiceName)
	if err = c.validate(); err != nil {
		return nil, nil, err
	}
	var base http.RoundTripper = otelhttp.NewTransport(http.DefaultTransport)
	if f := currentBaseFactory(); f != nil {
		if custom := f(name, c); custom != nil {
			base = custom
		}
	}
	resource := httpResourceLabel(c)
	exec := resilience.ExecutorFor(resource)
	tcfg := c.toTransportConfig(base, exec)
	if wrappers := currentTransportWrappers(); len(wrappers) > 0 {
		tcfg.WrapTransport = func(rt http.RoundTripper) http.RoundTripper {
			for _, w := range slices.Backward(wrappers) {
				rt = w(name, c, rt)
			}
			return rt
		}
	}
	rt, closeFn, err = httpx.NewTransport(tcfg)
	if err != nil {
		log.Errorf(ctx.Context, starterTag, "http-client: create transport failed: %v", err)
		return nil, nil, err
	}
	return rt, closeFn, nil
}

// routeKey returns the dispatch key for an entry: its direct address, or its
// service name when routing through discovery. This is the Target a generated
// client sets, and the value dispatchTransport matches against req.Host.
func routeKey(c Config) string {
	if c.Addr != "" {
		return c.Addr
	}
	return c.ServiceName
}

// httpResourceLabel derives the governance resource label for an http client,
// scoped to the service name (discovery mode) or address (direct mode).
func httpResourceLabel(c Config) string {
	return resilience.ResourceLabel("http", c.ServiceName, c.Addr)
}

// destroyDispatch releases every route's discovery watch and resilience
// executor by closing the dispatch transport.
func destroyDispatch(d *dispatchTransport) error {
	log.Debugf(context.Background(), starterTag, "http client destroyed")
	return d.Close()
}

// dispatchTransport routes each request by req.Host to the transport assembled
// for that target. It is the single process-wide transport installed by
// replacing httpclt.DoRequest; Close releases every route's resources.
type dispatchTransport struct {
	mu      sync.RWMutex
	routes  map[string]http.RoundTripper
	closers []func() error
}

func (d *dispatchTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	d.mu.RLock()
	rt := d.routes[req.Host]
	d.mu.RUnlock()
	if rt == nil {
		return nil, errutil.Explain(nil, "http-client: no transport for target %q", req.Host)
	}
	return rt.RoundTrip(req)
}

func (d *dispatchTransport) Close() error {
	for _, closeFn := range d.closers {
		if err := closeFn(); err != nil {
			return err
		}
	}
	return nil
}
